### ISSUE TITLE
Rounding errors causing problems

### ISSUE THREAD

**Issue by cssinate** [JZechy/satisfactory-manager#10]
**Describe the bug**
Inaccurate rounding is causing numbers to not line up correctly

**To Reproduce**
Look here: https://satisfactory.fandom.com/wiki/Heavy_Modular_Frame
The alternative recipe, "Heavy Encased Frame" shows the output is `2.8125` items per minute. Your website shows `2.80`.
As a specific example, let's look at the Encased Industrial Beams (EIB) requirement for this recipe. The recipe shows `9.375` EIB per second are required. Your website shows `9.40`.
If we use the alternative recipe "Encased Industrial Pipes", the output from an Assembler is 4 EIB per minute. `9.375 / 4 = 2.34375`. So we need 3 Assemblers: 2 at `100%` and 1 at `34.375%`. The underclocked factory should be producing `1.375` EIB, and the website shows `1.38`.
If I add all these buildings to my factory, it shows that I'm short on EIB, when the math says that shouldn't be the case.

**Expected behavior**
Satisfactory uses as many as 4 decimal places in their production chains (I couldn't find examples of more). This tool should use *at least* that many, but perhaps more.

**Screenshots**
![image](https://user-images.githubusercontent.com/25226452/119187998-12c14600-ba48-11eb-876c-869ed1d926c2.png)

**Comment by JZechy** [comment]
It's not rounding issue (the tool is not rouding recipies numbers) but wrong definition of it. 

Every recipe is written down by hand. And this remnant of times before Update 4, it is possible some recipies are unchanged as I don't how many recipies was changed.

HMF recipies are repaired and live.
