### ISSUE TITLE
UI Issue in Beta

### ISSUE THREAD

**Issue by cssinate** [JZechy/satisfactory-manager#12]
**Is your feature request related to a problem? Please describe.**
**Describe the bug**
When editing a building in a factory in the beta version of the app, the X for deleting the building and the X for closing the modal are close together. More than once, I couldn't figure out where my building went after editing it, realizing I must have clicked the wrong X.

**Describe the solution you'd like**
When you first click Edit Factory, the buildings are listed in little tiles. I think the red X would be fine on these tiles. However, once you're editing a building, consider changing it to a red-colored link that says, "Delete this building" at the bottom of the building edit screen.

![image](https://user-images.githubusercontent.com/25226452/119881338-2e6e9580-befb-11eb-9b30-08c453272d98.png)

**Comment by Flachdachs** [comment]
see also #7

**Comment by JZechy** [comment]
This was already mentioned in #7 as @Flachdachs pointed.
