### ISSUE TITLE
Can't select purity resource nodes

### ISSUE THREAD

**Issue by jefmen908** [JZechy/satisfactory-manager#2]
If you select the miner. It wil standard use the impure number. You can not select a another impurity.

**Comment by jefmen908** [comment]
also for the Resource Well Extractors and the Oil Extractor 
![IMG_6154 1](https://user-images.githubusercontent.com/82841861/115296471-4a905180-a15b-11eb-93ea-d0a22a7e0cab.JPG)
![IMG_6153 1](https://user-images.githubusercontent.com/82841861/115296499-53812300-a15b-11eb-84d8-69561fdc2a8b.JPG)

**Comment by JZechy** [comment]
Confirmed, such a bad mistake... Repair will be tommorrow morning (CEST) ASAP

**Comment by JZechy** [comment]
Confirmed and repair is live!
