### ISSUE TITLE
Crash - Nothing being displayed when  choosing Oscillator Recipe

### ISSUE THREAD

**Issue by d3rwilly** [JZechy/satisfactory-manager#3]
**Describe the bug**
When choosing the standard recipe for the Oscillator the Screen wenn’s black After the reloading.
This Screen stays until you delete the coockies. 

**To Reproduce**
Place a Manufacturer and choose the Crystal Oscillator Standard recipe.

**Desktop (please complete the following information):**
 - OS: Windows 10 and IOS
 - Browser Opera (both  times)
 - safari
 - Maybe others too

**Comment by JZechy** [comment]
Thanks for report, there will be some error in recipe, Will report soon as I can.

**Comment by JZechy** [comment]
@d3rwilly thanks once again for the report, oscillator recipe is repaired and live.
