### ISSUE TITLE
Invalid values for TurboMotor

### ISSUE THREAD

**Issue by Mekevesi** [JZechy/satisfactory-manager#4]
Invalid values.
Now is
![Screenshot_1](https://user-images.githubusercontent.com/83465563/116721123-42e36f00-a9dd-11eb-9fe7-c920f06740c5.jpg)
Should be
![Screenshot_2](https://user-images.githubusercontent.com/83465563/116721336-79b98500-a9dd-11eb-84fc-98b7aedf2605.jpg)

**Comment by JZechy** [comment]
Isn't that only parts to make a single turbomotor? All values in mamager are **per minute**

**Comment by Mekevesi** [comment]
You have right. But you can change from alternate to normal because the wrong description is.


![Screenshot_1](https://user-images.githubusercontent.com/83465563/116747364-11c76680-a9fe-11eb-9739-01b1adf14f0a.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/83465563/116747371-14c25700-a9fe-11eb-8f47-848c48071f58.jpg)

**Comment by JZechy** [comment]
Most of late game recipes updates are based on gamepedia, so it possible 😅 repair will be Done

**Comment by JZechy** [comment]
You probably have older version of the game, according to [Satisfactory Calculator](https://satisfactory-calculator.com/en/items/detail/id/Desc_MotorLightweight_C/name/Turbo+Motor) and [Satisfactory Gamepedia](https://satisfactory.fandom.com/wiki/Turbo_Motor), the standard recipe for Turbo Motor consists of:

- Cooling System
- Radio Control Unit
- Motor
- Rubber

I have also verified the recipe by game itself (using actual steam version).
