### ISSUE TITLE
Missing recipe Electrode - Aluminum Scrap

### ISSUE THREAD

**Issue by jefmen908** [JZechy/satisfactory-manager#5]
Placing refinery and selecting alternate Electrode - Aluminum Scrap. Screen went black.

**Comment by JZechy** [comment]
Thanks for report, probably some mistake in recipe definition. Will be repaired.

**Comment by JZechy** [comment]
@jefmen908 Thanks once again for the report, the Electrode-Aluminum Scrap recipe is repaired and live.
