### ISSUE TITLE
Alternate: Adhered Iron Plate recipe is not correct

### ISSUE THREAD

**Issue by PCasafont** [JZechy/satisfactory-manager#9]
https://github.com/JZechy/satisfactory-manager/blob/7206b0381da88512752366484a69b656b0527521/src/Data/Recipes.tsx#L672

```
			ingredients: {
				ironPlate: 11.25
				rubber: 3.75
			},
			products: {
				reinforcedIronPlate: 3.75
			}
```

**Comment by JZechy** [comment]
Actually [it is](https://satisfactory-calculator.com/en/items/detail/id/Desc_IronPlateReinforced_C/name/Reinforced+Iron+Plate), numbers ar representing units per minut not single input.

**Comment by PCasafont** [comment]
Are you sure that recipe is producing rubber?

**Comment by JZechy** [comment]
@PCasafont Next time:

- Describe your issue
- Make suggestions via Pull Requests, where is diff view.

I couldn't recognize your intentions by this way. Recipe is repaired and live.

**Comment by PCasafont** [comment]
Sorry, it was very late in the night 😅 thank you!
